spring:
  application:
    name: msa-gateway
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Gateway-StartTime, '#{T(java.lang.System).currentTimeMillis()}'
      routes:
        - id: service-a
          uri: http://localhost:8081
          predicates:
            - Path=/api/service-a/**
          filters:
            - RewritePath=/api/service-a/(?<segment>.*), /api/$\{segment}
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/$\{segment}


logging:
  config: classpath:logback.xml

web:
  security:
    - /api/auth/**
    - /auth/**
  cors:
    - http://localhost:8080