spring:
  application:
    name: msa-gateway
  cloud:
    gateway:
      # ? ??? ?? ?? ???? ??????, Deprecated ??? ???? 'default-filters' ??
      default-filters:
        # ? SpEL ?? ??? ?????.
        - AddRequestHeader=X-Gateway-StartTime, '#{T(java.lang.System).currentTimeMillis()}'

      # ? 'routes' ?? ??? ?? ?? ????? ???? ?? ?? ??? ??
      routes:
        - id: service-a
          uri: http://localhost:8081
          predicates:
            - Path=/api/service-a/**
          filters:
            - RewritePath=/api/service-a/(?<segment>.*), /api/$\{segment}
        - id: service-b
          uri: http://localhost:8082
          predicates:
            - Path=/api/service-b/**
          filters:
            - RewritePath=/api/service-a/(?<segment>.*), /api/$\{segment}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server.HttpServer: DEBUG